-- Users table (extends Supabase Auth)
CREATE TABLE DIVYA_USERS (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  SUPABASE_UID    VARCHAR2(255) UNIQUE NOT NULL,
  ROLE            VARCHAR2(20) DEFAULT 'devotee'
                    CONSTRAINT chk_role CHECK (ROLE IN ('devotee','pandit','super_admin','ceo')),
  FULL_NAME       VARCHAR2(255) NOT NULL,
  PHONE           VARCHAR2(20) UNIQUE,
  AVATAR_URL      VARCHAR2(2000),
  PREFERRED_LANG  VARCHAR2(5) DEFAULT 'hi',
  GOTRA           VARCHAR2(100),
  NAKSHATRA       VARCHAR2(50),
  RASHI           VARCHAR2(50),
  OCCUPATION      VARCHAR2(100),
  TOTAL_DONATED   NUMBER(15,2) DEFAULT 0,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_TEMPLES (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  PANDIT_ID       RAW(16) NOT NULL REFERENCES DIVYA_USERS(ID),
  NAME            VARCHAR2(500) NOT NULL,
  NAME_HI         VARCHAR2(500),
  DESCRIPTION     CLOB,
  DEITY           VARCHAR2(200),
  ADDRESS         VARCHAR2(1000),
  VILLAGE         VARCHAR2(200),
  DISTRICT        VARCHAR2(200),
  STATE           VARCHAR2(100),
  PINCODE         VARCHAR2(10),
  LATITUDE        NUMBER(10,7),
  LONGITUDE       NUMBER(10,7),
  LOCATION        SDO_GEOMETRY,
  COVER_PHOTO_URL VARCHAR2(2000),
  PHOTO_URLS      CLOB,                  -- JSON array
  IS_VERIFIED     NUMBER(1) DEFAULT 0,
  IS_ACTIVE       NUMBER(1) DEFAULT 1,
  QR_CODE_URL     VARCHAR2(2000),
  QR_TOKEN        VARCHAR2(100) UNIQUE DEFAULT RAWTOHEX(SYS_GUID()),
  DEVOTEE_COUNT   NUMBER(10) DEFAULT 0,
  RATING          NUMBER(3,2) DEFAULT 0,
  REVIEW_COUNT    NUMBER(10) DEFAULT 0,
  AI_SUMMARY      CLOB,                  -- Gemini-generated temple summary
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Oracle Spatial index for nearby temple search
INSERT INTO USER_SDO_GEOM_METADATA VALUES (
  'DIVYA_TEMPLES','LOCATION',
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('LON',-180,180,0.005),
    SDO_DIM_ELEMENT('LAT',-90,90,0.005)
  ), 4326
);
CREATE INDEX idx_temples_spatial ON DIVYA_TEMPLES(LOCATION) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

CREATE TABLE DIVYA_TEMPLE_MEMBERS (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  TEMPLE_ID       RAW(16) NOT NULL REFERENCES DIVYA_TEMPLES(ID) ON DELETE CASCADE,
  USER_ID         RAW(16) NOT NULL REFERENCES DIVYA_USERS(ID) ON DELETE CASCADE,
  FAMILY_SIZE     NUMBER(3) DEFAULT 1,
  VILLAGE         VARCHAR2(200),
  JOINED_VIA      VARCHAR2(20) DEFAULT 'qr',
  IS_ACTIVE       NUMBER(1) DEFAULT 1,
  JOINED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT uq_member UNIQUE (TEMPLE_ID, USER_ID)
);

CREATE TABLE DIVYA_DONATION_DRIVES (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  TEMPLE_ID       RAW(16) NOT NULL REFERENCES DIVYA_TEMPLES(ID) ON DELETE CASCADE,
  TITLE           VARCHAR2(500) NOT NULL,
  TITLE_HI        VARCHAR2(500),
  DESCRIPTION     CLOB,
  PUJA_TYPE       VARCHAR2(200),
  COVER_PHOTO_URL VARCHAR2(2000),
  TARGET_AMOUNT   NUMBER(15,2) NOT NULL,
  RAISED_AMOUNT   NUMBER(15,2) DEFAULT 0,
  MIN_DONATION    NUMBER(10,2) DEFAULT 1,
  DEADLINE        DATE,
  EVENT_DATE      TIMESTAMP,
  EVENT_LOCATION  VARCHAR2(500),
  STATUS          VARCHAR2(20) DEFAULT 'active',
  NOTE_FOR_DONORS CLOB,
  AI_DESCRIPTION  CLOB,                  -- Gemini-written drive appeal
  CREATED_BY      RAW(16) REFERENCES DIVYA_USERS(ID),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_DONATIONS (
  ID                    RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  DRIVE_ID              RAW(16) NOT NULL REFERENCES DIVYA_DONATION_DRIVES(ID),
  TEMPLE_ID             RAW(16) NOT NULL REFERENCES DIVYA_TEMPLES(ID),
  DONOR_ID              RAW(16) REFERENCES DIVYA_USERS(ID),
  AMOUNT                NUMBER(15,2) NOT NULL,
  CURRENCY              VARCHAR2(5) DEFAULT 'INR',
  IS_ANONYMOUS          NUMBER(1) DEFAULT 0,
  PAYMENT_METHOD        VARCHAR2(50),
  RAZORPAY_ORDER_ID     VARCHAR2(200),
  RAZORPAY_PAYMENT_ID   VARCHAR2(200) UNIQUE,
  RAZORPAY_SIGNATURE    VARCHAR2(500),
  STATUS                VARCHAR2(20) DEFAULT 'pending',
  NOTES                 VARCHAR2(1000),
  CREATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_DRIVE_EXPENSES (
  ID          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  DRIVE_ID    RAW(16) NOT NULL REFERENCES DIVYA_DONATION_DRIVES(ID) ON DELETE CASCADE,
  CATEGORY    VARCHAR2(100),  -- flowers, prasad, dakshina, bhandara, decoration, other
  AMOUNT      NUMBER(10,2) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  RECEIPT_URL VARCHAR2(2000),
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_PANDIT_PROFILES (
  ID                RAW(16) PRIMARY KEY REFERENCES DIVYA_USERS(ID),
  DISPLAY_NAME      VARCHAR2(255) NOT NULL,
  BIO               CLOB,
  BIO_HI            CLOB,
  EXPERIENCE_YEARS  NUMBER(3) DEFAULT 0,
  SPECIALISATIONS   CLOB,            -- JSON array of puja types
  LANGUAGES         CLOB,            -- JSON array
  CITIES_SERVED     CLOB,            -- JSON array
  IS_VERIFIED       NUMBER(1) DEFAULT 0,
  RATING            NUMBER(3,2) DEFAULT 0,
  TOTAL_PUJAS       NUMBER(10) DEFAULT 0,
  REVIEW_COUNT      NUMBER(10) DEFAULT 0,
  BASE_PRICE        NUMBER(10,2),
  PHOTO_URL         VARCHAR2(2000),
  IS_AVAILABLE      NUMBER(1) DEFAULT 1,
  ACCEPTS_REMOTE    NUMBER(1) DEFAULT 1,
  ACCEPTS_HOME      NUMBER(1) DEFAULT 1,
  AI_REVIEW_SUMMARY CLOB,            -- Gemini-generated review summary
  CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_PUJA_SERVICES (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  TEMPLE_ID       RAW(16) REFERENCES DIVYA_TEMPLES(ID),
  PANDIT_ID       RAW(16) NOT NULL REFERENCES DIVYA_PANDIT_PROFILES(ID),
  PUJA_NAME       VARCHAR2(500) NOT NULL,
  PUJA_NAME_HI    VARCHAR2(500),
  PUJA_TYPE       VARCHAR2(200) NOT NULL,
  DESCRIPTION     CLOB,
  DURATION_HOURS  NUMBER(4,1),
  BASE_PRICE      NUMBER(10,2) NOT NULL,
  PRASAD_PRICE    NUMBER(10,2) DEFAULT 0,
  BHOG_PRICE      NUMBER(10,2) DEFAULT 0,
  IS_REMOTE       NUMBER(1) DEFAULT 1,
  IS_HOME         NUMBER(1) DEFAULT 1,
  IS_ACTIVE       NUMBER(1) DEFAULT 1,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_PUJA_BOOKINGS (
  ID                    RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  BOOKING_TYPE          VARCHAR2(10) NOT NULL,       -- remote, home
  SERVICE_ID            RAW(16) REFERENCES DIVYA_PUJA_SERVICES(ID),
  PANDIT_ID             RAW(16) NOT NULL REFERENCES DIVYA_PANDIT_PROFILES(ID),
  TEMPLE_ID             RAW(16) REFERENCES DIVYA_TEMPLES(ID),
  DEVOTEE_ID            RAW(16) NOT NULL REFERENCES DIVYA_USERS(ID),
  SANKALP_NAME          VARCHAR2(500) NOT NULL,
  SANKALP_GOTRA         VARCHAR2(200),
  SANKALP_NAKSHATRA     VARCHAR2(100),
  SANKALP_RASHI         VARCHAR2(50),
  SANKALP_FATHER        VARCHAR2(500),
  SANKALP_PURPOSE       VARCHAR2(200),
  FAMILY_NAMES          CLOB,                        -- JSON array
  SPECIAL_WISH          CLOB,
  SCHEDULED_DATE        DATE NOT NULL,
  SCHEDULED_SLOT        VARCHAR2(20),
  MUHURAT_NOTE          VARCHAR2(500),
  HOME_ADDRESS          CLOB,
  HOME_CITY             VARCHAR2(200),
  HOME_PINCODE          VARCHAR2(10),
  WANTS_PRASAD          NUMBER(1) DEFAULT 1,
  PRASAD_ADDRESS        CLOB,
  PRASAD_TYPE           VARCHAR2(50) DEFAULT 'standard',
  STATUS                VARCHAR2(50) DEFAULT 'pending',
  PUJA_AMOUNT           NUMBER(10,2) NOT NULL,
  PRASAD_AMOUNT         NUMBER(10,2) DEFAULT 0,
  DELIVERY_AMOUNT       NUMBER(10,2) DEFAULT 0,
  PLATFORM_FEE          NUMBER(10,2) DEFAULT 0,
  TOTAL_AMOUNT          NUMBER(10,2) NOT NULL,
  RAZORPAY_ORDER_ID     VARCHAR2(200),
  RAZORPAY_PAYMENT_ID   VARCHAR2(200),
  PAYMENT_STATUS        VARCHAR2(20) DEFAULT 'pending',
  ESCROW_RELEASE_AT     TIMESTAMP,
  PAYMENT_RELEASED_AT   TIMESTAMP,
  PUJA_VIDEO_URL        VARCHAR2(2000),
  PROOF_PHOTO_URLS      CLOB,                        -- JSON array
  PANDIT_NOTES          CLOB,
  COURIER_NAME          VARCHAR2(200),
  COURIER_TRACKING_ID   VARCHAR2(200),
  COURIER_TRACKING_URL  VARCHAR2(2000),
  DISPATCHED_AT         TIMESTAMP,
  DELIVERED_AT          TIMESTAMP,
  DEVOTEE_RATING        NUMBER(1),
  DEVOTEE_REVIEW        CLOB,
  REVIEWED_AT           TIMESTAMP,
  AI_SANKALP_SUMMARY    CLOB,
  AI_PUJA_NOTES         CLOB,
  AI_PROOF_SCORE        NUMBER(5,2),
  CREATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_PANDIT_AVAILABILITY (
  ID          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  PANDIT_ID   RAW(16) NOT NULL REFERENCES DIVYA_PANDIT_PROFILES(ID),
  AVAIL_DATE  DATE NOT NULL,
  SLOT        VARCHAR2(20) NOT NULL,   -- morning, afternoon, evening, full_day
  IS_BOOKED   NUMBER(1) DEFAULT 0,
  BOOKING_ID  RAW(16) REFERENCES DIVYA_PUJA_BOOKINGS(ID),
  CONSTRAINT uq_avail UNIQUE (PANDIT_ID, AVAIL_DATE, SLOT)
);

CREATE TABLE DIVYA_REVIEWS (
  ID          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  PANDIT_ID   RAW(16) NOT NULL REFERENCES DIVYA_PANDIT_PROFILES(ID),
  BOOKING_ID  RAW(16) UNIQUE REFERENCES DIVYA_PUJA_BOOKINGS(ID),
  REVIEWER_ID RAW(16) NOT NULL REFERENCES DIVYA_USERS(ID),
  RATING      NUMBER(1) NOT NULL,
  PUJA_TYPE   VARCHAR2(200),
  REVIEW_TEXT CLOB,
  IS_VISIBLE  NUMBER(1) DEFAULT 1,
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_ANNOUNCEMENTS (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  TEMPLE_ID       RAW(16) NOT NULL REFERENCES DIVYA_TEMPLES(ID) ON DELETE CASCADE,
  PANDIT_ID       RAW(16) NOT NULL REFERENCES DIVYA_USERS(ID),
  TITLE           VARCHAR2(500) NOT NULL,
  BODY            CLOB NOT NULL,
  PHOTO_URL       VARCHAR2(2000),
  PRANAM_COUNT    NUMBER(10) DEFAULT 0,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_LIVE_STREAMS (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  TEMPLE_ID       RAW(16) NOT NULL REFERENCES DIVYA_TEMPLES(ID),
  PANDIT_ID       RAW(16) NOT NULL REFERENCES DIVYA_USERS(ID),
  TITLE           VARCHAR2(500) NOT NULL,
  STREAM_KEY      VARCHAR2(200) UNIQUE,
  PLAYBACK_URL    VARCHAR2(2000),
  THUMBNAIL_URL   VARCHAR2(2000),
  STATUS          VARCHAR2(20) DEFAULT 'scheduled',
  VIEWER_COUNT    NUMBER(10) DEFAULT 0,
  SCHEDULED_AT    TIMESTAMP,
  STARTED_AT      TIMESTAMP,
  ENDED_AT        TIMESTAMP,
  RECORDING_URL   VARCHAR2(2000),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_NOTIFICATIONS (
  ID          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  USER_ID     RAW(16) NOT NULL REFERENCES DIVYA_USERS(ID) ON DELETE CASCADE,
  NOTIF_TYPE  VARCHAR2(100) NOT NULL,
  TITLE       VARCHAR2(500) NOT NULL,
  BODY        CLOB NOT NULL,
  DATA_JSON   CLOB,                    -- JSON payload for deep linking
  IS_READ     NUMBER(1) DEFAULT 0,
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_PUSH_TOKENS (
  ID          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  USER_ID     RAW(16) NOT NULL REFERENCES DIVYA_USERS(ID) ON DELETE CASCADE,
  TOKEN       VARCHAR2(500) NOT NULL UNIQUE,
  PLATFORM    VARCHAR2(10),
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_CHATBOT_SESSIONS (
  ID          RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  USER_ID     RAW(16) NOT NULL REFERENCES DIVYA_USERS(ID),
  MESSAGES    CLOB NOT NULL,
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_AI_LOGS (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  USER_ID         RAW(16) REFERENCES DIVYA_USERS(ID),
  FEATURE         VARCHAR2(100) NOT NULL,
  MODEL           VARCHAR2(100),
  INPUT_TOKENS    NUMBER(10) DEFAULT 0,
  OUTPUT_TOKENS   NUMBER(10) DEFAULT 0,
  LATENCY_MS      NUMBER(10),
  SUCCESS         NUMBER(1) DEFAULT 1,
  ERROR_MSG       VARCHAR2(2000),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_FRAUD_FLAGS (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  ENTITY_TYPE     VARCHAR2(50),      -- donation, booking, temple, user
  ENTITY_ID       RAW(16),
  RISK_SCORE      NUMBER(5,2),       -- 0-100
  RISK_LEVEL      VARCHAR2(20),      -- low, medium, high, critical
  RISK_REASONS    CLOB,              -- JSON array
  AI_EXPLANATION  CLOB,
  STATUS          VARCHAR2(20) DEFAULT 'pending',
  REVIEWED_BY     RAW(16) REFERENCES DIVYA_USERS(ID),
  REVIEWER_NOTE   CLOB,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DIVYA_PLATFORM_METRICS (
  ID              RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  METRIC_DATE     DATE NOT NULL,
  METRIC_TYPE     VARCHAR2(100),
  METRIC_VALUE    NUMBER(20,4),
  BREAKDOWN_JSON  CLOB,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ORACLE ORDS: Enable REST on schema
BEGIN
  ORDS.ENABLE_SCHEMA(
    p_enabled => TRUE, p_schema => 'DIVYA',
    p_url_mapping_type => 'BASE_PATH',
    p_url_mapping_pattern => 'divya',
    p_auto_rest_auth => FALSE
  );
  COMMIT;
END;
/

-- TRIGGERS
CREATE OR REPLACE TRIGGER trg_devotee_count
AFTER INSERT OR UPDATE OR DELETE ON DIVYA_TEMPLE_MEMBERS FOR EACH ROW
BEGIN
  UPDATE DIVYA_TEMPLES SET
    DEVOTEE_COUNT = (SELECT COUNT(*) FROM DIVYA_TEMPLE_MEMBERS
                     WHERE TEMPLE_ID = COALESCE(:NEW.TEMPLE_ID,:OLD.TEMPLE_ID) AND IS_ACTIVE=1)
  WHERE ID = COALESCE(:NEW.TEMPLE_ID,:OLD.TEMPLE_ID);
END;
/
