/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-tint": "#af3017",
        "primary-fixed-dim": "#ffb4a4",
        "on-tertiary-fixed": "#2b1700",
        "primary-fixed": "#ffdad3",
        "secondary": "#a43a37",
        "secondary-fixed-dim": "#ffb3ad",
        "on-secondary-container": "#721416",
        "surface-container-highest": "#e3e2e0",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1a1c1a",
        "background": "#faf9f6",
        "tertiary-fixed": "#ffdcbb",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f312f",
        "on-tertiary": "#ffffff",
        "tertiary": "#855000",
        "outline": "#8d716b",
        "primary": "#ab2e15",
        "surface-dim": "#dbdad7",
        "outline-variant": "#e1bfb8",
        "surface-container-high": "#e9e8e5",
        "primary-container": "#cd462b",
        "inverse-primary": "#ffb4a4",
        "on-tertiary-container": "#fffbff",
        "surface-container": "#efeeeb",
        "on-background": "#1a1c1a",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#410004",
        "on-secondary-fixed-variant": "#842322",
        "on-error": "#ffffff",
        "secondary-container": "#fd7c75",
        "surface-bright": "#faf9f6",
        "tertiary-fixed-dim": "#ffb869",
        "on-primary": "#ffffff",
        "on-surface-variant": "#59413c",
        "on-primary-fixed": "#3e0500",
        "on-primary-fixed-variant": "#8d1701",
        "on-tertiary-fixed-variant": "#673d00",
        "surface-container-low": "#f4f3f1",
        "error": "#ba1a1a",
        "surface": "#faf9f6",
        "secondary-fixed": "#ffdad7",
        "inverse-on-surface": "#f2f1ee",
        "accent": "#BA7517"
      },
      fontFamily: {
        "headline": ["Noto Serif"],
        "body": ["Inter"],
        "label": ["Inter"],
        "serif": ["Noto Serif"],
        "sans": ["Noto Sans"]
      },
    },
  },
  plugins: [],
};
